name: tpd-base
channels:
    - defaults
    - conda-forge
    - bioconda
dependencies:
    - conda-forge::procps-ng
    - python
    - click
    - seqkit
    - samtools
    - pandas
    - biopython
    - csvtk
    - wget
    - pigz
    - unzip
    - pymummer
    - hmmer
    - dfast
    - russel88::cctyper